version: '3.9'
services:
  db:
    build: .
    restart: always
    ports:
      - "3306:3306"  # Correct port mapping for MySQL
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

